openapi: "3.1.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://api.example.com/v1/
paths:
  /:
    get:
      summary: Root
      operationId: root
      tags:
        - root
      responses:
        200:
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                - $ref: "#/components/schemas/basic"
components:
  schemas:
    name:
      type: object
      required:
        - data
        - length
      properties:
        data:
          type: string
        length:
          type: int
    basic:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: object
          required:
            - preferred
            - full
          properties:
            preferred:
              type: object
              schema:
                $ref: "#/components/schemas/name"
            full:
              type: object
              required:
                - first
                - middle
                - last
              properties:
                first:
                  type: object
                  schema:
                    $ref: "#/components/schemas/name"
                middle:
                  type: object
                  schema:
                    $ref: "#/components/schemas/name"
                last:
                  type: object
                  schema:
                    $ref: "#/components/schemas/name"
